INSERT INTO plates (code, name, info) VALUES ('SC', 'Scotia', 'South-Atlantic');
INSERT INTO plates (code, name, info) VALUES ('AT', 'Antarctic', null);
INSERT INTO plates (code, name, info) VALUES ('AF', 'African', null);
INSERT INTO plates (code, name, info) VALUES ('AR', 'Arabian', null);
INSERT INTO plates (code, name, info) VALUES ('CO', 'Cocos', 'Central America coast, Pacific side');
INSERT INTO plates (code, name, info) VALUES ('EA', 'Eurasian', null);
INSERT INTO plates (code, name, info) VALUES ('IN', 'Indian', null);
INSERT INTO plates (code, name, info) VALUES ('AU', 'Australian', null);
INSERT INTO plates (code, name, info) VALUES ('JF', 'Juan de Fuca', 'North-West US and Western Canada coast');
INSERT INTO plates (code, name, info) VALUES ('CA', 'Caribbean', null);
INSERT INTO plates (code, name, info) VALUES ('NA', 'North-American', null);
INSERT INTO plates (code, name, info) VALUES ('NZ', 'Nazca', 'Western South-American coast');
INSERT INTO plates (code, name, info) VALUES ('PA', 'Pacific', null);
INSERT INTO plates (code, name, info) VALUES ('FI', 'Filipino', null);
INSERT INTO plates (code, name, info) VALUES ('SA', 'South-American', null);